feat: Added Dockerfile to ElevAIte

diff --git a/nextapps/elevaite/Dockerfile b/nextapps/elevaite/Dockerfile
--- a/nextapps/elevaite/Dockerfile
+++ b/nextapps/elevaite/Dockerfile
@@ -7,7 +7,7 @@ RUN apk update
 WORKDIR /app
 RUN yarn global add turbo
 COPY . .
-RUN turbo prune web --docker
+RUN turbo prune elevaite --docker
  
 # Add lockfile and package.json's of isolated subworkspace
 FROM base AS installer
@@ -18,28 +18,43 @@ WORKDIR /app
 # First install the dependencies (as they change less often)
 COPY .gitignore .gitignore
 COPY --from=builder /app/out/json/ .
-COPY --from=builder /app/out/yarn.lock ./yarn.lock
-RUN yarn install
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
  
 # Build the project
 COPY --from=builder /app/out/full/ .
-RUN yarn turbo run build --filter=web...
+COPY turbo.json turbo.json
+RUN npx --yes turbo run build --filter=elevaite...
  
 FROM base AS runner
 WORKDIR /app
+
+ENV NODE_ENV production
+ENV NEXT_TELEMETRY_DISABLED 1
  
 # Don't run production as root
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 nextjs
 USER nextjs
  
-COPY --from=installer /app/apps/web/next.config.js .
-COPY --from=installer /app/apps/web/package.json .
+COPY --from=installer /app/nextapps/elevaite/next.config.js .
+COPY --from=installer /app/nextapps/elevaite/package.json .
  
 # Automatically leverage output traces to reduce image size
 # https://nextjs.org/docs/advanced-features/output-file-tracing
-COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
-COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
-COPY --from=installer --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public
+COPY --from=installer --chown=nextjs:nodejs /app/nextapps/elevaite/.next/standalone ./
+COPY --from=installer --chown=nextjs:nodejs /app/nextapps/elevaite/.next/static ./nextapps/elevaite/.next/static
+COPY --from=installer --chown=nextjs:nodejs /app/nextapps/elevaite/public ./nextapps/elevaite/public
+
+USER nextjs
+
+EXPOSE 3000
+
+ENV PORT 3000
  
-CMD node apps/web/server.js
+CMD node nextapps/elevaite/server.js
